### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by JMuff22** [boutetnico/ansible-role-influxdb#16]
Version 5.0.0 does not work due to InfluxDB signing key URL changing:

```
TASK [boutetnico.influxdb : Manage InfluxData APT repositories] ****************
failed: [monitoring-instance] (item=deb https://repos.influxdata.com/ubuntu focal stable) => {"ansible_loop_var": "item", "changed": false, "item": "deb https://repos.influxdata.com/ubuntu focal stable", "msg": "Failed to update apt cache: W:GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E, E:The repository 'https://repos.influxdata.com/ubuntu focal InRelease' is not signed."}
```

This was fixed in https://github.com/boutetnico/ansible-role-influxdb/commit/8fb28b3b5dfad932845b3e479f66aa28e23d8443 but a new release has not been created yet. Is is possible for a new release and version on ansible-galaxy be published? Thanks.

Current fix is to use role directly from github.

**Comment by boutetnico** [comment]
Thanks @JMuff22 for bringing this up, new release [5.0.1](https://github.com/boutetnico/ansible-role-influxdb/releases/tag/5.0.1) is out.
