### ISSUE TITLE
Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by michaelbaisch** [boutetnico/ansible-role-influxdb#7]
Hello,

when using this role configured with TLS like so:

```
influxdb_config:
  tls-cert: "/etc/letsencrypt/live/{{ my_domain }}/fullchain.pem"
  tls-key: "/etc/letsencrypt/live/{{ my_domain }}/privkey.pem"
```

I get an error on the task `Ensure InfluxDB is up and running`:

```
Error: Got 400 from 'http://localhost:8086/health', Attempted to unmarshal error as JSON but failed: invalid character 'C' looking for beginning of value: Client sent an HTTP request to an HTTPS server.
```

This error will also happen on `Set InfluxDB default user, organization, and bucket` when the last one is disabled. 

The way I understand it is as follows: as long as the configuration (in `/root/.influxdbv2/configs`) with a correct host isn't created, which is done with the `influx setup`, the `influx` command will use the default host `http://localhost:8086/`. That will not work with TLS, because it should be `https` and the domain is wrong. The way I found to fix that was to use the `--host` argument in those two tasks like so: 

```
- name: Ensure InfluxDB is up and running
  command: influx ping \
    --host {{ influxdb_host}}
  retries: 10
  delay: 5
  register: _ping
  until: _ping.rc == 0
  changed_when: false

- name: Set InfluxDB default user, organization, and bucket
  command: influx setup \
    --org {{ influxdb_primary_org }} \
    --bucket {{ influxdb_primary_bucket }} \
    --username {{ influxdb_primary_username }} \
    --password {{ influxdb_primary_password }} \
    --token {{ influxdb_admin_token }} \
    --host {{ influxdb_host}} \
    --force
  register: _setup
  failed_when:
    - _setup.rc != 0
    - '"has already been setup" not in _setup.stdout'
  changed_when: _setup.rc == 0
```

`influxdb_host` could be a variable of the role, which is by default set to `http://localhost:8086/`

Any thoughts on that suggestion?

Greetings Michael

**Comment by boutetnico** [comment]
Hello @michaelbaisch,

I have prepared a [PR](https://github.com/boutetnico/ansible-role-influxdb/pull/8) to address this issue.

The approach I took is to dynamically find out if TLS by `influxd` is used and adapt `host` on every `influx` command accordingly.

Feel free to let me know if that works for you.

**Comment by michaelbaisch** [comment]
Hi @boutetnico 

thanks for the response!

The problem with the PR for me is that the host is hardcoded to `localhost`. Since I'm using a Lets Encrypt Certificate this won't work: 

```
sudo influx ping --host "https://localhost:8086"
Error: Get "https://localhost:8086/health": x509: certificate is valid for *my-domain*, not localhost.
Error: Get "https://localhost:8086/api/v2/setup": x509: certificate is valid for  *my-domain*, not localhost.
```

**Comment by boutetnico** [comment]
@michaelbaisch Thanks for your reply.
I have followed your idea and added `influxdb_host` which defaults to `http://localhost:8086`.

**Comment by michaelbaisch** [comment]
Looks good to me. Thank you!

**Comment by boutetnico** [comment]
Thanks @michaelbaisch for helping on this!
